---
- name: Create a k8s namespace
  kubernetes.core.k8s:
    name: rabbitmq
    api_version: v1
    kind: Namespace
    state: present

- name: Install RabbitMQ Chart
  kubernetes.core.helm:
    name: rabbitmq
    namespace: rabbitmq
    chart_ref: stable/rabbitmq
